#!/bin/bash
set -e
DOT_DIRECTORY="${HOME}/dotfiles"
DOT_TARBALL="https://github.com/chaingng/dotfiles/tarball/master"
REMOTE_URL="git@github.com:chaingng/dotfiles.git"

has() {
  type "$1" > /dev/null 2>&1
}

usage() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]

Commands:
  deploy
  initialize

Arguments:
  -f $(tput setaf 1)** warning **$(tput sgr0) Overwrite dotfiles.
  -h Print help (this message)
EOF
  exit 1
}

while getopts :f:h opt; do
  case ${opt} in
    f)
      OVERWRITE=true
      ;;
    h)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

# Working only OS X.
case ${OSTYPE} in
  darwin*)
    ;;
  *)
    echo $(tput setaf 1)Working only OS X!!$(tput sgr0)
    exit 1
    ;;
esac

# If missing, download and extract the dotfiles repository
if [ ! -d ${DOT_DIRECTORY} ]; then
  echo "Downloading dotfiles..."
  mkdir ${DOT_DIRECTORY}

  if has "git"; then
    git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
  else
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOT_TARBALL}
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOT_DIRECTORY}
    rm -f ${HOME}/dotfiles.tar.gz
  fi

  echo $(tput setaf 2)Download dotfiles complete!. ✔︎$(tput sgr0)
fi

cd ${DOT_DIRECTORY}

link_files() {
  for f in .??*
  do
    # Force remove the vim directory if it's already there
    [ -n "${OVERWRITE}" -a -e ${HOME}/${f} ] && rm -f ${HOME}/${f}
    if [ ! -e ${HOME}/${f} ]; then
      [[ ${f} = ".git" ]] && continue
      [[ ${f} = ".gitignore" ]] && continue
      ln -snfv ${DOT_DIRECTORY}/"$f" ${HOME}/"$f"
    fi
  done

  echo $(tput setaf 2)Deploy dotfiles complete!. ✔︎$(tput sgr0)
}

initialize() {

  [ ! -d ${HOME}/.tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm

  # install brew
  if has "brew"; then
    echo "brew already installed"
  else
    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
    sudo mv homebrew /opt/
    export PATH=/opt/homebrew/bin:$PATH
  fi

  if [ ! -d ${HOME}/env_private ]; then
    touch ${HOME}/env_private
  fi
  
  if [ ! -d ${HOME}/.rbenv ]; then
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  fi


  # curl -o ${HOME}/.zsh/git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
  # curl -o ${HOME}/.zsh/git-completion.zsh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh 
  # curl -o ${HOME}/.zsh/_git https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh

  exit

  if has "pyenv"; then
    echo "pyenv already installed"
  else
    git clone git://github.com/yyuu/pyenv.git ${HOME}/.pyenv
    . ${HOME}/.zshenv
    pyenv install 3.8.7
    pyenv global
    . ${HOME}/.zshenv
  fi

  curl -O https://download.java.net/java/ga/jdk11/openjdk-11_osx-x64_bin.tar.gz
  tar xvzf openjdk-11_osx-x64_bin.tar.gz
  sudo mv jdk-11.jdk /Library/Java/JavaVirtualMachines/
  export JAVA_HOME=`/usr/libexec/java_home -v 11`

  

  set +e
  if has "nodebrew"; then
    nodebrew install-binary latest && nodebrew use latest
  fi
  if has "rbenv"; then
    [ ! -d $(rbenv root)/plugins/rbenv-default-gems ] && git clone -q https://github.com/rbenv/rbenv-default-gems.git $(rbenv root)/plugins/rbenv-default-gems
    [ ! -e $(rbenv root)/default-gems ] && cp ${DOT_DIRECTORY}/default-gems $(rbenv root)/default-gems
    latest=`rbenv install -l | grep -v - | tail -n 1 | tr -d ' '`
    if ! rbenv versions | grep -e "${latest}\( \|$\)"; then
      rbenv install ${latest}
      rbenv global ${latest}
    fi
  fi

  sudo mkdir -p /usr/local/git/contrib/completion/
  cp /usr/local/Cellar/git/`git --version | awk '{print $3}'`/etc/bash_completion.d/git-completion.bash ./
  mv git-completion.bash /usr/local/git/contrib/completion/

  brew install git

  echo "$(tput setaf 2)Initialize complete!. ✔︎$(tput sgr0)"
}

command=$1
[ $# -gt 0 ] && shift

case $command in
  deploy)
    link_files
    ;;
  init*)
    initialize
    ;;
  *)
    usage
    ;;
esac

exit 0
